version: '3.8'
services:
  authdb:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB1_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/authdb_init.sql:/docker-entrypoint-initdb.d/authdb_init.sql
      - authdbdata:/var/lib/postgresql/data

volumes:
  authdbdata:
